# This workflow will run pytest only

name: Run pytest

on:
  push:
  pull_request:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        python:
        - "3.9"
        - "3.13"
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test with pytest
        run: |
          pytest
